PsHelloAzure/Models/Course.cs
using Newtonsoft.Json;
using System.Collections.Generic;

namespace PsHelloAzure.Models
{
    public class Course
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        public string Title { get; set; }
        public ICollection<Module> Modules { get; set; }
    }

    public class Module
    {
        public string Title { get; set; }
        public ICollection<Clip> Clips { get; set; }
    }

    public class Clip
    {
        public string Name { get; set; }
        public int Length { get; set; }
    }

    public class SampleData
    {
        public IEnumerable<Course> GetCourses()
        {
            yield return new Course
            {
                Title = "Azure for .NET Developers",
                Modules = new List<Module>
                {
                    new Module
                    {
                        Title = "Introduction to Azure",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Overview" },
                            new Clip { Length = 35, Name = "Azure Portal" },
                            new Clip { Length = 30, Name = "Virtual Machines" }
                        }
                    },
                    new Module
                    {
                        Title = "Cloud Databases",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Overview" },
                            new Clip { Length = 35, Name = "Azure SQL" },
                            new Clip { Length = 30, Name = "Cosmos DB" }
                        }
                    }
                }
            };

            yield return new Course
            {
                Title = "Building Secure Services in Azure",
                Modules = new List<Module>
                {
                    new Module
                    {
                        Title = "Azure AD",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Creating Apps" },
                            new Clip { Length = 35, Name = "Using OIDC" },
                            new Clip { Length = 30, Name = "Managing users" }
                        }
                    },

                    new Module
                    {
                        Title = "Azure Resource Manager",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Automation!" },
                            new Clip { Length = 35, Name = "ARM Templates" },
                        }
                    }
                }
            };

            yield return new Course
            {
                Title = "ASP.NET Core Fundamentals",
                Modules = new List<Module>
                {
                    new Module
                    {
                        Title = "Introduction to ASP.NET Core",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Overview" },
                            new Clip { Length = 35, Name = "dotnet" },
                            new Clip { Length = 30, Name = "Startup" }
                        }
                    },

                    new Module
                    {
                        Title = "Middleware",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Overview" },
                            new Clip { Length = 35, Name = "RequestDelegates" },
                            new Clip { Length = 30, Name = "HttpContext" },
                            new Clip { Length = 30, Name = "Building a pipeline" }
                        }
                    },

                    new Module
                    {
                        Title = "Controllers",
                        Clips =  new List<Clip>
                        {
                            new Clip { Length = 30, Name = "Overview" },
                            new Clip { Length = 35, Name = "Building APIs" },
                            new Clip { Length = 30, Name = "Processing JSON" }
                        }
                    }
                }
            };
        }
    }
}

PsHelloAzure/Models/ErrorViewModel.cs
using System;

namespace PsHelloAzure.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PsHelloAzure/Models/ShowModel.cs
namespace PsHelloAzure.Models
{
    public class ShowModel
    {
        public string Uri { get; set; }
    }
}

PsHelloAzure/Controllers/CoursesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PsHelloAzure.Models;
using PsHelloAzure.Services;

namespace PsHelloAzure.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CourseStore _courseStore;

        public CoursesController(CourseStore courseStore)
        {
            _courseStore = courseStore;
        }

        public IActionResult Index()
        {
            var model = _courseStore.GetAllCourses();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Insert()
        {
            var data = new SampleData().GetCourses();
            await _courseStore.InsertCourses(data);
            return RedirectToAction(nameof(Index));
        }
    }
}

PsHelloAzure/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using PsHelloAzure.Models;

namespace PsHelloAzure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IConfiguration _configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            var model = _configuration["Greeting"];
            return View("Index", model);
        }

        public IActionResult Test()
        {
            throw new InvalidOperationException("Sorry, this feature is not supported.");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PsHelloAzure/Controllers/ImagesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PsHelloAzure.Models;
using PsHelloAzure.Services;

namespace PsHelloAzure.Controllers
{
    [Route("[controller]/[action]")]
    public class ImagesController : Controller
    {
        private readonly ImageStore _imageStore;

        public ImagesController(ImageStore imageStore)
        {
            _imageStore = imageStore;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(IFormFile image)
        {
            if (image != null)
            {
                using (var stream = image.OpenReadStream())
                {
                    var imageId = await _imageStore.SaveImage(stream);
                    return RedirectToAction("Show", new { imageId });
                }
            }
            return View();
        }

        [HttpGet("{imageId}")]
        public ActionResult Show(string imageId)
        {
            var model = new ShowModel { Uri = _imageStore.UriFor(imageId) };
            return View(model);
        }
    }
}

PsHelloAzure/Views/Courses/Index.cshtml
@model IEnumerable<Course>
@{
    ViewData["Title"] = "Courses";
}

<h2>All Courses</h2>

@if (Model.Any())
{
    <table class="table">
        @foreach (var course in Model)
        {
            <tr>
                <td>@course.Title</td>
                <td>@course.Id</td>
                <td>
                    <table class="table table-condensed">
                        @foreach (var module in course.Modules)
                        {
                            <tr>
                                <td>@module.Title</td>
                                <td>
                                    <table class="table table-condensed">
                                        @foreach (var clip in module.Clips)
                                        {
                                            <tr>
                                                <td>@clip.Name</td>
                                                <td>@(clip.Length)m</td>
                                            </tr>

                                        }
                                    </table>
                                </td>
                            </tr>

                        }
                    </table>
                </td>
            </tr>

        }
    </table>
}
else
{
    <div>No courses to display</div>
    <form asp-action="Insert">
        <input type="submit"
               class="btn btn-primary"
               value="Insert Sample Courses" />
    </form>
}

PsHelloAzure/Views/Home/Index.cshtml
@model string
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h3>@Model</h3>

PsHelloAzure/Views/Images/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Upload an Image</h2>

<form method="post" enctype="multipart/form-data" asp-action="Upload">
    <input type="file" name="image" />
    <hr />
    <input class="btn btn-primary" type="submit" value="Go!" />
</form>

PsHelloAzure/Views/Images/Show.cshtml
@model ShowModel
@{
    ViewData["Title"] = "Show";
}

<h2>Your Image</h2>
<img src="@Model.Uri" />

PsHelloAzure/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PsHelloAzure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PsHelloAzure</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Images" asp-action="Index">Images</a></li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PsHelloAzure - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>